openapi: 3.0.0
info:
  title: Ably Chat REST API
  version: 1.0.0
paths:
  /rooms/{roomId}/messages:
    get:
      summary: Retrieve messages from a room
      parameters:
        - name: roomId
          in: path
          required: true
          description: The unique identifier of the room you wish to query history for. This should be URI encoded.
          schema:
            type: string
        - name: limit
          in: query
          description: Maximum number of messages to be retrieved in one request.
          schema:
            type: integer
        - name: orderBy
          in: query
          description: The order in which to return the messages; either oldestFirst or newestFirst.
          schema:
            type: string
        - name: serial
          in: query
          description: The serial value of the message to start fetching from.
          schema:
            type: string
        - name: direction
          in: query
          description: The direction to fetch messages from; either forwards or backwards.
          schema:
            type: string
        - name: envelope
          in: query
          description: The format of the response; either json or msgpack.
          schema:
            type: string
        - name: X-Ably-ClientId
          in: header
          description: The unique identifier of the client making the request.
          schema:
            type: string
        - name: X-Ably-Version
          in: header
          description: The version of the Ably API to use. Current latest version is 3.
          schema:
            type: string
        - name: authorization
          in: header
          description: The token to authenticate the request.
          schema:
            type: string
      responses:
        '200':
          description: A list of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    serial:
                      type: string
                    version:
                      type: string
                    roomId:
                      type: string
                    text:
                      type: string
                    clientId:
                      type: string
                    action:
                      type: string
                    metadata:
                      type: object
                    headers:
                      type: object
                    createdAt:
                      type: integer
                    timestamp:
                      type: integer
                    reactions:
                      type: object
        'default':
          description: Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    post:
      summary: Send a message to a room
      parameters:
        - name: roomId
          in: path
          required: true
          description: The unique identifier of the room. This should be URI encoded.
          schema:
            type: string
        - name: envelope
          in: query
          description: The format of the response; either json or msgpack.
          schema:
            type: string
        - name: X-Ably-ClientId
          in: header
          description: The unique identifier of the client making the request.
          schema:
            type: string
        - name: X-Ably-Version
          in: header
          description: The version of the Ably protocol to use.
          schema:
            type: string
        - name: authorization
          in: header
          description: The token to authenticate the request.
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                headers:
                  type: object
                metadata:
                  type: object
      responses:
        '200':
          description: Message sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  serial:
                    type: string
                  createdAt:
                    type: string
        'default':
          description: Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /rooms/{roomId}/occupancy:
    get:
      summary: Fetch the occupancy of a room
      parameters:
        - name: roomId
          in: path
          required: true
          description: The unique identifier of the room you wish to query history for. This should be URI encoded.
          schema:
            type: string
        - name: envelope
          in: query
          description: The format of the response; either json or msgpack.
          schema:
            type: string
        - name: X-Ably-ClientId
          in: header
          description: The unique identifier of the client making the request.
          schema:
            type: string
        - name: X-Ably-Version
          in: header
          description: The version of the Ably API protocol to use.
          schema:
            type: string
        - name: authorization
          in: header
          description: The token to authenticate the request.
          schema:
            type: string
      responses:
        '200':
          description: Occupancy metrics for the room
          content:
            application/json:
              schema:
                type: object
                properties:
                  connections:
                    type: integer
                  presenceMembers:
                    type: integer
        'default':
          description: Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /rooms/{roomId}/messages/{serial}:
    put:
      summary: Update a message in a room
      parameters:
        - name: roomId
          in: path
          required: true
          description: The unique identifier of the room. This should be URI encoded.
          schema:
            type: string
        - name: serial
          in: path
          required: true
          description: The unique identifier of the message you wish to update. This should be URI encoded.
          schema:
            type: string
        - name: envelope
          in: query
          description: The format of the response; either json or msgpack.
          schema:
            type: string
        - name: X-Ably-ClientId
          in: header
          description: The unique identifier of the client making the request.
          schema:
            type: string
        - name: X-Ably-Version
          in: header
          description: The version of the Ably protocol to use.
          schema:
            type: string
        - name: authorization
          in: header
          description: The token to authenticate the request.
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: object
                  properties:
                    text:
                      type: string
                    headers:
                      type: object
                    metadata:
                      type: object
                description:
                  type: string
                metadata:
                  type: object
      responses:
        '201':
          description: Message updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                  timestamp:
                    type: string
        'default':
          description: Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /rooms/{roomId}/messages/{serial}/delete:
    post:
      summary: Delete a message in a room
      parameters:
        - name: roomId
          in: path
          required: true
          description: The unique identifier of the room. This should be URI encoded.
          schema:
            type: string
        - name: serial
          in: path
          required: true
          description: The unique identifier of the message you wish to delete. This should be URI encoded.
          schema:
            type: string
        - name: envelope
          in: query
          description: The format of the response; either json or msgpack.
          schema:
            type: string
        - name: X-Ably-ClientId
          in: header
          description: The unique identifier of the client making the request.
          schema:
            type: string
        - name: X-Ably-Version
          in: header
          description: The version of the Ably protocol to use.
          schema:
            type: string
        - name: authorization
          in: header
          description: The token to authenticate the request.
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                metadata:
                  type: object
      responses:
        '200':
          description: Message deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                  timestamp:
                    type: string
        'default':
          description: Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
