version: '3.0'
services:
  webserver:
    build:
      context: .
      args:
        RUBY_VERSION: 2.7.1
    ports:
    - "4000:4000"
    volumes:
    - .:/docs/app
    command: 'bundle exec nanoc live -p 4000 -o 0.0.0.0'
