#!/bin/bash

IMAGE="ably/docs:latest"

DOCKER_VER=$(docker version -f '{{.Server.Version}}')
DOCKER_VER_MAJOR=$(echo $DOCKER_VER |cut -d'.' -f1)
DOCKER_VER_MINOR=$(echo $DOCKER_VER |cut -d'.' -f2)

if ((DOCKER_VER_MAJOR < 2)); then
  if ((DOCKER_VER_MINOR < 12)); then
    echo "Docker version 1.12 or greater is required. You are running $DOCKER_VER_MAJOR.$DOCKER_VER_MINOR"
    echo "Mounting volumes in older versions with the host on Mac/Windows was not possible prior to this"
    exit 1
  fi
fi

case "$1" in
  -b|--build|build)
    docker build --tag $IMAGE .
    ;;

  -c|--compile|compile)
    docker run --rm -v "$(pwd)":/docs/app $IMAGE 'bundle exec nanoc'
    ;;

  -s|--server|server)
    docker run --rm -v "$(pwd)":/docs/app -p 4000:4000 $IMAGE 'bundle exec nanoc view -p 4000'
    ;;

  -g|--guard|guard)
    docker run --rm -v "$(pwd)":/docs/app -i -t $IMAGE 'guard'
    ;;

  *)
    echo "Usage: docker-run CMD"
    echo "CMD supports:"
    echo "  build    - Build the docker image"
    echo "  compile  - Compile the static HTML for this site"
    echo "  guard    - Monitor changes and recompile immediately if any files change (normally run concurrently with server)"
    echo "  server   - Compile and run the web server"
    exit 1 ;;
esac

exit 0
