packages:
  - .

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - core-js-pure
  - es5-ext
  - lmdb
  - msgpackr-extract
  - msw
  - v8-profiler-next

onlyBuiltDependencies:
  - gatsby
  - gatsby-cli
  - sharp
