// docs design tokens — originally @ably/ui's Tailwind theme, now owned locally
// (DX-1128). gui-disabled-* alias gui-unavailable for the disabled-state classes.
module.exports = {
  content: [
    './src/pages/docs/*.{ts,tsx}',
    './src/components/**/*.{ts,tsx}',
    './src/templates/**/*.{ts,tsx}',
    './node_modules/@ably/ui/core/**/*.{js,json}',
  ],
  safelist: [{ pattern: /^hljs.*/ }],
  darkMode: ['selector', '.ui-theme-dark'],
  theme: {
    screens: {
      xs: '428px',
      sm: '768px',
      md: '1040px',
      lg: '1280px',
      xl: '1440px',
    },
    fontFamily: {
      sans_next: ['NEXT Book', 'Arial', 'Helvetica', 'sans-serif'],
      serif: ['ui-serif', 'Georgia', 'Cambria', 'Times New Roman', 'Times', 'serif'],
      mono_source_code: ['Source Code Pro', 'Courier', 'monospace'],
      sans: [
        'Manrope',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'BlinkMacSystemFont',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'Noto Sans',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
      ],
      mono: [
        'JetBrains Mono',
        'ui-monospace',
        'SFMono-Regular',
        'Menlo',
        'Monaco',
        'Consolas',
        'Liberation Mono',
        'Courier New',
        'monospace',
      ],
    },
    extend: {
      fontFamily: {
        serif: ['IBM Plex Serif', 'Georgia', 'Cambria', 'Times New Roman', 'Times', 'serif'],
      },
      colors: {
        'neutral-000': 'var(--color-neutral-000)',
        'neutral-100': 'var(--color-neutral-100)',
        'neutral-200': 'var(--color-neutral-200)',
        'neutral-300': 'var(--color-neutral-300)',
        'neutral-400': 'var(--color-neutral-400)',
        'neutral-500': 'var(--color-neutral-500)',
        'neutral-600': 'var(--color-neutral-600)',
        'neutral-700': 'var(--color-neutral-700)',
        'neutral-800': 'var(--color-neutral-800)',
        'neutral-900': 'var(--color-neutral-900)',
        'neutral-1000': 'var(--color-neutral-1000)',
        'neutral-1100': 'var(--color-neutral-1100)',
        'neutral-1200': 'var(--color-neutral-1200)',
        'neutral-1300': 'var(--color-neutral-1300)',
        'orange-100': 'var(--color-orange-100)',
        'orange-200': 'var(--color-orange-200)',
        'orange-300': 'var(--color-orange-300)',
        'orange-400': 'var(--color-orange-400)',
        'orange-500': 'var(--color-orange-500)',
        'orange-600': 'var(--color-orange-600)',
        'orange-700': 'var(--color-orange-700)',
        'orange-800': 'var(--color-orange-800)',
        'orange-900': 'var(--color-orange-900)',
        'orange-1000': 'var(--color-orange-1000)',
        'orange-1100': 'var(--color-orange-1100)',
        'yellow-100': 'var(--color-yellow-100)',
        'yellow-200': 'var(--color-yellow-200)',
        'yellow-300': 'var(--color-yellow-300)',
        'yellow-400': 'var(--color-yellow-400)',
        'yellow-500': 'var(--color-yellow-500)',
        'yellow-600': 'var(--color-yellow-600)',
        'yellow-700': 'var(--color-yellow-700)',
        'yellow-800': 'var(--color-yellow-800)',
        'yellow-900': 'var(--color-yellow-900)',
        'green-100': 'var(--color-green-100)',
        'green-200': 'var(--color-green-200)',
        'green-300': 'var(--color-green-300)',
        'green-400': 'var(--color-green-400)',
        'green-500': 'var(--color-green-500)',
        'green-600': 'var(--color-green-600)',
        'green-700': 'var(--color-green-700)',
        'green-800': 'var(--color-green-800)',
        'green-900': 'var(--color-green-900)',
        'blue-100': 'var(--color-blue-100)',
        'blue-200': 'var(--color-blue-200)',
        'blue-300': 'var(--color-blue-300)',
        'blue-400': 'var(--color-blue-400)',
        'blue-500': 'var(--color-blue-500)',
        'blue-600': 'var(--color-blue-600)',
        'blue-700': 'var(--color-blue-700)',
        'blue-800': 'var(--color-blue-800)',
        'blue-900': 'var(--color-blue-900)',
        'violet-100': 'var(--color-violet-100)',
        'violet-200': 'var(--color-violet-200)',
        'violet-300': 'var(--color-violet-300)',
        'violet-400': 'var(--color-violet-400)',
        'violet-500': 'var(--color-violet-500)',
        'violet-600': 'var(--color-violet-600)',
        'violet-700': 'var(--color-violet-700)',
        'violet-800': 'var(--color-violet-800)',
        'violet-900': 'var(--color-violet-900)',
        'pink-100': 'var(--color-pink-100)',
        'pink-200': 'var(--color-pink-200)',
        'pink-300': 'var(--color-pink-300)',
        'pink-400': 'var(--color-pink-400)',
        'pink-500': 'var(--color-pink-500)',
        'pink-600': 'var(--color-pink-600)',
        'pink-700': 'var(--color-pink-700)',
        'pink-800': 'var(--color-pink-800)',
        'pink-900': 'var(--color-pink-900)',
        'gui-blue-default-light': 'var(--color-gui-blue-default-light)',
        'gui-blue-hover-light': 'var(--color-gui-blue-hover-light)',
        'gui-blue-active-light': 'var(--color-gui-blue-active-light)',
        'gui-blue-default-dark': 'var(--color-gui-blue-default-dark)',
        'gui-blue-hover-dark': 'var(--color-gui-blue-hover-dark)',
        'gui-blue-active-dark': 'var(--color-gui-blue-active-dark)',
        'gui-blue-focus': 'var(--color-gui-blue-focus)',
        'gui-blue-visited': 'var(--color-gui-blue-focus)',
        'gui-unavailable': 'var(--color-gui-unavailable)',
        'gui-unavailable-dark': 'var(--color-gui-unavailable-dark)',
        'gui-disabled-light': 'var(--color-gui-disabled-light)',
        'gui-disabled-dark': 'var(--color-gui-disabled-dark)',
        'gui-success-green': 'var(--color-gui-success-green)',
        'gui-error-red': 'var(--color-gui-error-red)',
        'gui-focus': 'var(--color-gui-focus)',
        'gui-focus-outline': 'var(--color-gui-focus-outline)',
        transparent: 'transparent',
        'cool-black': 'var(--color-neutral-1300)',
        'active-orange': 'var(--color-orange-600)',
        'red-orange': 'var(--color-orange-800)',
        white: 'var(--color-neutral-000)',
        'electric-cyan': 'var(--color-blue-400)',
        'zingy-green': 'var(--color-green-400)',
        'bright-red': 'var(--color-orange-700)',
        'jazzy-pink': 'var(--color-pink-500)',
        'extra-light-grey': 'var(--color-neutral-100)',
        'light-grey': 'var(--color-neutral-200)',
        'mid-grey': 'var(--color-neutral-500)',
        'dark-grey': 'var(--color-neutral-800)',
        'charcoal-grey': 'var(--color-neutral-1000)',
        'gui-default': 'var(--color-gui-blue-default-light)',
        'gui-hover': 'var(--color-gui-blue-hover-light)',
        'gui-active': 'var(--color-gui-blue-active-light)',
        'gui-default-dark': 'var(--color-gui-blue-default-dark)',
        'gui-hover-dark': 'var(--color-gui-blue-hover-dark)',
        'gui-active-dark': 'var(--color-gui-blue-active-dark)',
        'gui-alt': 'var(--color-neutral-1300)',
        'gui-error': 'var(--color-gui-error-red)',
        'gui-success': 'var(--color-gui-success-green)',
        'icon-linkedin': 'var(--icon-color-linkedin)',
        'icon-twitter': 'var(--icon-color-twitter)',
        'icon-glassdoor': 'var(--icon-color-glassdoor)',
        'icon-github': 'var(--icon-color-github)',
        'icon-discord': 'var(--icon-color-discord)',
      },
      fontSize: {
        title: ['var(--fs-title)', 'var(--lh-min-normal)'],
        'title-xl': ['var(--fs-title-xl)', 'var(--lh-min-normal)'],
        'title-xs': ['var(--fs-title-xs)', 'var(--lh-min-normal)'],
        h1: ['var(--fs-h1)', 'var(--lh-dense)'],
        'h1-xl': ['var(--fs-h1-xl)', 'var(--lh-min-normal)'],
        'h1-xs': ['var(--fs-h1-xs)', 'var(--lh-min-normal)'],
        h2: ['var(--fs-h2)', 'var(--lh-min-normal)'],
        'h2-xl': ['var(--fs-h2-xl)', 'var(--lh-min-normal)'],
        'h2-xs': ['var(--fs-h2-xs)', 'var(--lh-min-normal)'],
        h3: ['var(--fs-h3)', 'var(--lh-min-normal)'],
        h4: ['var(--fs-h4)', 'var(--lh-min-normal)'],
        h5: ['var(--fs-h5)', 'var(--lh-min-normal)'],
        p1: ['var(--fs-p1)', 'var(--lh-relaxed)'],
        p2: ['var(--fs-p2)', 'var(--lh-relaxed)'],
        p3: ['var(--fs-p3)', 'var(--lh-relaxed)'],
        p4: ['var(--fs-p4)', 'var(--lh-relaxed)'],
        standfirst: ['var(--fs-standfirst)'],
        'standfirst-xl': ['var(--fs-standfirst-xl)'],
        'sub-header': ['var(--fs-sub-header)'],
        'sub-header-xs': ['var(--fs-sub-header-xs)'],
        overline1: ['var(--fs-overline1)'],
        overline2: ['var(--fs-overline2)'],
        label1: ['var(--fs-label1)', 'var(--lh-snug)'],
        label2: ['var(--fs-label2)', 'var(--lh-snug)'],
        label3: ['var(--fs-label3)', 'var(--lh-snug)'],
        label4: ['var(--fs-label4)', 'var(--lh-snug)'],
        quote: ['var(--fs-quote)'],
        code: ['var(--fs-code)', 'var(--lh-none)'],
        code2: ['var(--fs-code2)', 'var(--lh-none)'],
      },
      backgroundImage: {
        'gradient-active-orange': 'var(--gradient-active-orange)',
        'gradient-hot-pink': 'var(--gradient-hot-pink)',
        'gradient-priority-button': 'var(--gradient-priority-button)',
      },
      borderRadius: {
        md: '0.1875rem',
        DEFAULT: '0.375rem',
      },
      transitionProperty: {
        input: 'background-color, box-shadow',
      },
      dropShadow: {
        toggle: ['0 4px 4px rgba(0,0,0,0.25)', '0 4px 8px rgba(0,0,0,0.15)'],
      },
      outline: {
        'gui-focus': '1.5px solid var(--color-gui-focus-outline)',
      },
      borderWidth: {
        btn: '1.5px',
      },
      gridTemplateColumns: {
        dynamic:
          'repeat(var(--dynamic-grid-columns-count), minmax(var(--dynamic-grid-column-min-width), var(--dynamic-grid-column-max-width)))',
        'header-layout': '173px minmax(200px, 400px) 1fr',
      },
      lineHeight: {
        dense: 'var(--lh-dense)',
        snug: 'var(--lh-snug)',
        relaxed: 'var(--lh-relaxed)',
      },
      padding: {
        btn: 'var(--spacing-btn)',
        'btn-small': 'var(--spacing-btn-small)',
        'btn-xsmall': 'var(--spacing-btn-xsmall)',
        'btn-large': 'var(--spacing-btn-large)',
        'menu-row': 'var(--spacing-menu-row)',
        'menu-row-snug': 'var(--spacing-menu-row-snug)',
        'menu-row-title': 'var(--spacing-menu-row-title)',
        media: 'var(--spacing-media)',
        input: 'var(--spacing-input)',
      },
      boxShadow: {
        subtle: '0px 1px 0px var(--color-neutral-500)',
        tooltip: '0px 5px 10px 0px #00000022',
        container: '0px 40px 40px rgba(0, 0, 0, 0.1)',
        'container-subtle': '0px 16px 64px rgba(0, 0, 0, 0.1)',
        input: '0px 0px 8px 0px rgba(8, 103, 196, 1)', // color-gui-hover at 50%
        quote: '0rem 1.5rem 2rem 0rem #0000000d',
      },
      keyframes: {
        tooltipEntry: {
          '0%': { transform: 'translateY(8px)', opacity: 0 },
          '100%': { transform: 'translateY(0)', opacity: 1 },
        },
        tooltipExit: {
          '0%': { opacity: 1 },
          '100%': { opacity: 0 },
        },
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'fade-in-ten-percent': {
          from: { opacity: 0 },
          to: { opacity: 0.1 },
        },
        'fade-out-ten-percent': {
          from: { opacity: 0.1 },
          to: { opacity: 0 },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'rotateX(-10deg) scale(0.9)' },
          to: { opacity: '1', transform: 'rotateX(0deg) scale(1)' },
        },
        'scale-out': {
          from: { opacity: '1', transform: 'rotateX(0deg) scale(1)' },
          to: { opacity: '0', transform: 'rotateX(-10deg) scale(0.95)' },
        },
        'enter-from-right': {
          from: { opacity: '0', transform: 'translateX(200px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        'enter-from-left': {
          from: { opacity: '0', transform: 'translateX(-200px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        'exit-to-right': {
          from: { opacity: '1', transform: 'translateX(0)' },
          to: { opacity: '0', transform: 'translateX(200px)' },
        },
        'exit-to-left': {
          from: { opacity: '1', transform: 'translateX(0)' },
          to: { opacity: '0', transform: 'translateX(-200px)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'scale-in': 'scale-in 200ms ease',
        'scale-out': 'scale-out 200ms ease',
        'enter-from-left': 'enter-from-left 250ms ease',
        'enter-from-right': 'enter-from-right 250ms ease',
        'exit-to-left': 'exit-to-left 250ms ease',
        'exit-to-right': 'exit-to-right 250ms ease',
      },
    },
    listStyleType: {
      none: 'none',
      disc: 'disc',
      decimal: 'decimal',
      square: 'square',
      circle: 'circle',
    },
  },
  corePlugins: {
    preflight: false,
  },
  plugins: [require('@tailwindcss/container-queries')],
};
