export const data = {
  hero: {
    title: 'Available SDKs',
    subtitle: "Ably's SDKs provide a consistent and idiomatic API across a variety of supported platforms.",
  },
  tabs: {
    channels: {
      text: "Choose from the following list of SDKs to build an application using the Pub/Sub Channels product. Click 'Setup' for instructions on getting started with an SDK, or view its source repository for a full list of the platforms it supports.",
      cards: [
        {
          title: 'JavaScript',
          text: 'Ably SDK for JavaScript.',
          image: { src: '/images/sdks/js.svg', isWide: false },
          githubRepoURL: 'https://github.com/ably/ably-js',
          setupLink: '/getting-started/setup?lang=javascript',
        },
        {
          title: 'Java',
          text: 'Ably SDK for Java.',
          image: { src: '/images/sdks/java.svg', isWide: false },
          githubRepoURL: 'https://github.com/ably/ably-java',
          setupLink: '/getting-started/setup?lang=java',
        },
        {
          title: 'Python',
          text: 'Ably SDK for Python.',
          image: { src: '/images/sdks/python.svg', isWide: false },
          githubRepoURL: 'https://github.com/ably/ably-python',
          setupLink: '/getting-started/setup?lang=python',
        },
        {
          title: 'React',
          text: 'Ably React Hooks package.',
          image: { src: '/images/sdks/react.svg', isWide: false },
          githubRepoURL: 'https://github.com/ably/ably-js',
          setupLink: '/getting-started/react',
        },
        {
          title: 'C#.NET',
          text: 'Ably SDK for C#.NET.',
          image: { src: '/images/sdks/csharp.svg', isWide: false },
          githubRepoURL: 'https://github.com/ably/ably-dotnet',
          setupLink: '/getting-started/setup?lang=csharp',
        },
        {
          title: 'Go',
          text: 'Ably SDK for Go.',
          image: { src: '/images/sdks/go.svg', isWide: false },
          githubRepoURL: 'https://github.com/ably/ably-go',
          setupLink: '/getting-started/setup?lang=go',
        },
        {
          title: 'Node.js',
          text: 'Ably SDK for Node.js.',
          image: { src: '/images/sdks/nodejs.svg', isWide: false },
          githubRepoURL: 'https://github.com/ably/ably-js',
          setupLink: '/getting-started/setup?lang=nodejs',
        },
        {
          title: 'Ruby',
          text: 'Ably SDK for Ruby.',
          image: { src: '/images/sdks/ruby.svg', isWide: false },
          githubRepoURL: 'https://github.com/ably/ably-ruby',
          setupLink: '/getting-started/setup?lang=ruby',
        },
        {
          title: 'Swift',
          text: 'Ably SDK for Swift.',
          image: { src: '/images/sdks/swift.svg', isWide: false },
          githubRepoURL: 'https://github.com/ably/ably-cocoa',
          setupLink: '/getting-started/setup?lang=swift',
        },
        {
          title: 'Objective-C',
          text: 'Ably SDK for Objective-C.',
          image: { src: '/images/sdks/objectivec.svg', isWide: false },
          githubRepoURL: 'https://github.com/ably/ably-cocoa',
          setupLink: '/getting-started/setup?lang=objc',
        },
        {
          title: 'Flutter',
          text: 'Ably SDK for Flutter.',
          image: { src: '/images/sdks/flutter.svg', isWide: false },
          githubRepoURL: 'https://github.com/ably/ably-flutter',
          setupLink: '/getting-started/setup?lang=flutter',
        },
        {
          title: 'PHP',
          text: 'Ably SDK for PHP.',
          image: { src: '/images/sdks/php.svg', isWide: false },
          githubRepoURL: 'https://github.com/ably/ably-php',
          setupLink: '/getting-started/setup?lang=php',
        },
        {
          title: 'PHP Laravel',
          text: 'Ably SDK for PHP Laravel.',
          image: { src: '/images/sdks/laravel.svg', isWide: false },
          githubRepoURL: 'https://github.com/ably/ably-php#laravel-realtime-broadcasting',
          setupLink: 'https://github.com/ably/ably-php#laravel-realtime-broadcasting',
        },
        {
          title: 'Android',
          text: 'Ably SDK for Android.',
          image: { src: '/images/sdks/android.svg', isWide: false },
          githubRepoURL: 'https://github.com/ably/ably-java',
          setupLink: '/getting-started/setup?lang=java',
        },
        {
          title: 'Kotlin',
          text: 'Ably SDK for Kotlin.',
          image: { src: '/images/sdks/kotlin.svg', isWide: false },
          githubRepoURL: 'https://github.com/ably/ably-java',
          setupLink: '/getting-started/setup?lang=java',
        },
        {
          title: 'Unity',
          text: 'Ably SDK for Unity.',
          image: { src: '/images/sdks/unity.svg', isWide: false },
          githubRepoURL: 'https://github.com/ably/ably-dotnet',
          setupLink: 'https://github.com/ably/ably-dotnet/blob/main/unity/README.md',
        },
        {
          title: 'Xamarin',
          text: 'Ably SDK for Xamarin.',
          image: { src: '/images/sdks/xamarin.svg', isWide: false },
          githubRepoURL: 'https://github.com/ably/ably-dotnet',
          setupLink: '/getting-started/setup?lang=csharp',
        },
        {
          title: 'NativeScript',
          text: 'Ably SDK for NativeScript.',
          image: { src: '/images/sdks/nativescript.svg', isWide: false },
          githubRepoURL: 'https://github.com/ably/ably-js-nativescript',
          setupLink: 'https://github.com/ably/ably-js-nativescript#how-to-use-this-library',
        },
        {
          title: 'Cordova',
          text: 'Ably SDK for Cordova.',
          image: { src: '/images/sdks/cordova.svg', isWide: false },
          githubRepoURL: 'https://github.com/ably/ably-js',
          setupLink: '/getting-started/setup?lang=javascript',
        },
        {
          title: 'Clojure',
          text: 'Ably SDK for Clojure.',
          image: { src: '/images/sdks/clojure.svg', isWide: false },
          githubRepoURL: 'https://github.com/ably/ably-java',
          setupLink: '/getting-started/setup?lang=java',
        },
        {
          title: 'Scala',
          text: 'Ably SDK for Scala.',
          image: { src: '/images/sdks/scala.svg', isWide: false },
          githubRepoURL: 'https://github.com/ably/ably-java',
          setupLink: '/getting-started/setup?lang=java',
        },
      ],
    },
    spaces: {
      text: "Choose from the following list of SDKs to add collaborative features to an application using the Spaces product. Click 'Setup' for instructions on getting started with an SDK, or view its source repository for a full list of the platforms it supports.",
      cards: [
        {
          title: 'JavaScript',
          text: 'Ably Spaces SDK for JavaScript.',
          image: { src: '/images/sdks/js.svg', isWide: false },
          githubRepoURL: 'https://github.com/ably/spaces',
          setupLink: '/spaces/setup',
        },
        {
          title: 'React',
          text: 'Ably Spaces React Hooks package.',
          image: { src: '/images/sdks/react.svg', isWide: false },
          githubRepoURL: 'https://github.com/ably/spaces',
          setupLink: '/spaces/react',
        },
      ],
    },
  },
};
